[project]
name = "myhn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.4",
    "requests>=2.32.3",
    "ruff>=0.11.10",
    "sqlmodel>=0.0.24",
]
